# PostgreSQL credentials for order-service database.

apiVersion: v1
kind: Secret
metadata:
  name: order-postgres-secret
  namespace: order-postgres
  labels:
    app.kubernetes.io/name: order-postgres
    app.kubernetes.io/component: secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: NWhCMjRyaTZNcThI
  POSTGRES_DB: b3JkZXJfZGI=
